# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Emanuel Betancur Villamil # The website title
first_name: Emanuel
middle_name:
last_name: Betancur Villamil
email: emanuelbe16@gmail.com
description: > # The ">" symbol means to ignore newlines until the next key
  Professional portfolio of Emanuel Betancur Villamil, a Mechatronics Engineer specializing in automation, robotics, and prototyping.
footer_text:
keywords: mechatronics, engineering, automation, robotics, prototyping, 3d-printing, portfolio-website # add your own keywords or leave empty

lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: 🤖 # the emoji used as the favicon

url: https://emanuel-bv.github.io # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/. Leave blank for root
last_updated: false # set to true if you want to display last updated in the footer
impressum_path:

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
max_width: 800px

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: Emanuel-BV # your GitHub user name
linkedin_username: emanuel-bv # your LinkedIn user name
# Add other social media usernames if you have them

contact_note: >
  The best way to contact me is via <a href="mailto:emanuelbe16@gmail.com">email</a>.

# -----------------------------------------------------------------------------
# Blog (Optional - can be configured later)
# -----------------------------------------------------------------------------

blog_name: Blog
blog_description: A collection of thoughts and projects.
permalink: /blog/:year/:title/

pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

# Giscus comments are disabled for now. You can set this up later.
giscus:
  repo:
  repo_id:
  category:
  category_id:
  mapping:
  strict: 0
  reactions_enabled: 0
  input_position: bottom
  theme: preferred_color_scheme
  emit_metadata: 0
  lang: en

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    enabled: true
    output: true
    permalink: /projects/:path/

announcements:
  enabled: true
  scrollable: true
  limit: 5

latest_posts:
  enabled: false
  limit: 3

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git

# Plug-ins
plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  # - jekyll-jupyter-notebook  <- REMOVED THIS LINE TO FIX THE BUILD
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  exclude: ['robots.txt']
  uglifier_args:
    harmony: true

# -----------------------------------------------------------------------------
# Jekyll Archives
# -----------------------------------------------------------------------------

jekyll-archives:
  enabled: [year, tags, categories]
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: '/blog/:year/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'

# -----------------------------------------------------------------------------
# Jekyll Scholar (for academic publications)
# -----------------------------------------------------------------------------

scholar:
  last_name: [Betancur Villamil]
  first_name: [Emanuel, E.]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"
  group_by: year
  group_order: descending

enable_publication_badges:
  altmetric: true
  dimensions: true

filtered_bibtex_keywords: [abbr, abstract, altmetric, arxiv, bibtex_show, blog, code, html, pdf, poster, preview, selected, slides, supp, video, website]
max_author_limit: 4
more_authors_animation_delay: 10
enable_publication_thumbnails: true

# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:

# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------

imagemagick:
  enabled: true
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
    - ".gif"
  output_formats:
    webp: "-quality 85"

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics:    false
enable_cronitor_analytics:  false
enable_google_verification: false
enable_bing_verification:   false
enable_masonry:             true
enable_math:                true
enable_tooltips:            false
enable_darkmode:            true
enable_navbar_social:       false
enable_project_categories:  true
enable_medium_zoom:         true
enable_progressbar:         true

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

bootstrap-table:
  version: "1.22.1"
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
mathjax:
  version: "3.2.0"
masonry:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
mdb:
  version: "4.20.0"
  integrity:
    css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
    js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
medium_zoom:
  version: "1.0.8"
  integrity: "sha256-7PhEpEWEW0XXQ0k6kQrPKwuoIomz8R8IYyuU1Qew4P8="

# -----------------------------------------------------------------------------
# Get external JSON data
# -----------------------------------------------------------------------------

jekyll_get_json:
  - data: resume
    json: assets/json/resume.json
jsonresume:
  - basics
  - work
  - education
  - publications
  - projects
  - volunteer
  - awards
  - certificates
  - skills
  - languages
  - interests
  - references
